spring.application.name=centro_donazione
# Configurazione del database MySQL
#spring.datasource.url=jdbc:mysql://root:vlZYNiyVDrZJLKNuLacPMmmfTJXMvqVe@shuttle.proxy.rlwy.net:16930/railway
spring.datasource.url=jdbc:postgresql://localhost:5432/centrodonazioni
spring.datasource.username=postgres
spring.datasource.password=password

# Driver JDBC di MySQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Dialetto Hibernate per MySQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Strategia di aggiornamento dello schema (equivalente a hbm2ddl.auto=update)
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create-drop

# Mostra le query SQL nel terminale
spring.jpa.show-sql=true
spring.main.allow-circular-references=true
