spring.application.name=centro_donazione
# Configurazione del database MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/donationcenter
spring.datasource.username=root
spring.datasource.password=password

# Driver JDBC di MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Dialetto Hibernate per MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Strategia di aggiornamento dello schema (equivalente a hbm2ddl.auto=update)
spring.jpa.hibernate.ddl-auto=none
#spring.jpa.hibernate.ddl-auto=create-drop

# Mostra le query SQL nel terminale
spring.jpa.show-sql=true
